### パラメータを含むURL
GET http://localhost:9000/routing/hi/ho

### クリストリングの束縛
GET http://localhost:9000/routing/params?param1=hey&param2=ho

### 固定値パラメータ
GET http://localhost:9000/routing/say/yay

### デフォルト値付きパラメータ(1)
GET http://localhost:9000/routing/params/with/defualt

### デフォルト値付きパラメータ(2)
GET http://localhost:9000/routing/params/with/defualt?param1=hey&param2=ho
