### パラメータを含むURL
GET http://localhost:9000/routing/hi/ho

### クリストリングの束縛
GET http://localhost:9000/routing/params?param1=hey&param2=ho

### 固定値パラメータ
GET http://localhost:9000/routing/say/yay

### デフォルト値付きパラメータ(1)
GET http://localhost:9000/routing/params/with/defualt

### デフォルト値付きパラメータ(2)
GET http://localhost:9000/routing/params/with/defualt?param1=hey&param2=ho

### オプションパラメータ(1)
GET http://localhost:9000/routing/params/as/option

### オプションパラメータ(2)
GET http://localhost:9000/routing/params/as/option?param1=hey&param2=ho

### 型付きパラメータ
GET http://localhost:9000/routing/123/as/int

### 複数値パラメータ
GET http://localhost:9000/routing/numbers/as/double?numbers=1.0&numbers=2.0

### 正規表現パターン
GET http://localhost:9000/routing/reg/123/X
